# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zorjen/proj/lar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zorjen/proj/lar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zorjen/proj/lar/CMakeFiles /home/zorjen/proj/lar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zorjen/proj/lar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyTests

# Build rule for target.
MyTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyTests
.PHONY : MyTests

# fast build rule for target.
MyTests/fast:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/build
.PHONY : MyTests/fast

#=============================================================================
# Target rules for targets named MyLibrary

# Build rule for target.
MyLibrary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyLibrary
.PHONY : MyLibrary

# fast build rule for target.
MyLibrary/fast:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/build
.PHONY : MyLibrary/fast

src/address.o: src/address.cc.o

.PHONY : src/address.o

# target to build an object file
src/address.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/address.cc.o
.PHONY : src/address.cc.o

src/address.i: src/address.cc.i

.PHONY : src/address.i

# target to preprocess a source file
src/address.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/address.cc.i
.PHONY : src/address.cc.i

src/address.s: src/address.cc.s

.PHONY : src/address.s

# target to generate assembly for a file
src/address.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/address.cc.s
.PHONY : src/address.cc.s

src/coroutine.o: src/coroutine.cc.o

.PHONY : src/coroutine.o

# target to build an object file
src/coroutine.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/coroutine.cc.o
.PHONY : src/coroutine.cc.o

src/coroutine.i: src/coroutine.cc.i

.PHONY : src/coroutine.i

# target to preprocess a source file
src/coroutine.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/coroutine.cc.i
.PHONY : src/coroutine.cc.i

src/coroutine.s: src/coroutine.cc.s

.PHONY : src/coroutine.s

# target to generate assembly for a file
src/coroutine.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/coroutine.cc.s
.PHONY : src/coroutine.cc.s

src/fdManager.o: src/fdManager.cc.o

.PHONY : src/fdManager.o

# target to build an object file
src/fdManager.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/fdManager.cc.o
.PHONY : src/fdManager.cc.o

src/fdManager.i: src/fdManager.cc.i

.PHONY : src/fdManager.i

# target to preprocess a source file
src/fdManager.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/fdManager.cc.i
.PHONY : src/fdManager.cc.i

src/fdManager.s: src/fdManager.cc.s

.PHONY : src/fdManager.s

# target to generate assembly for a file
src/fdManager.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/fdManager.cc.s
.PHONY : src/fdManager.cc.s

src/hook.o: src/hook.cc.o

.PHONY : src/hook.o

# target to build an object file
src/hook.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/hook.cc.o
.PHONY : src/hook.cc.o

src/hook.i: src/hook.cc.i

.PHONY : src/hook.i

# target to preprocess a source file
src/hook.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/hook.cc.i
.PHONY : src/hook.cc.i

src/hook.s: src/hook.cc.s

.PHONY : src/hook.s

# target to generate assembly for a file
src/hook.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/hook.cc.s
.PHONY : src/hook.cc.s

src/iomanager.o: src/iomanager.cc.o

.PHONY : src/iomanager.o

# target to build an object file
src/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/iomanager.cc.o
.PHONY : src/iomanager.cc.o

src/iomanager.i: src/iomanager.cc.i

.PHONY : src/iomanager.i

# target to preprocess a source file
src/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/iomanager.cc.i
.PHONY : src/iomanager.cc.i

src/iomanager.s: src/iomanager.cc.s

.PHONY : src/iomanager.s

# target to generate assembly for a file
src/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/iomanager.cc.s
.PHONY : src/iomanager.cc.s

src/scheduler.o: src/scheduler.cc.o

.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/scheduler.cc.o
.PHONY : src/scheduler.cc.o

src/scheduler.i: src/scheduler.cc.i

.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/scheduler.cc.i
.PHONY : src/scheduler.cc.i

src/scheduler.s: src/scheduler.cc.s

.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/scheduler.cc.s
.PHONY : src/scheduler.cc.s

src/socket.o: src/socket.cc.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/socket.cc.o
.PHONY : src/socket.cc.o

src/socket.i: src/socket.cc.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/socket.cc.i
.PHONY : src/socket.cc.i

src/socket.s: src/socket.cc.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/socket.cc.s
.PHONY : src/socket.cc.s

src/stream.o: src/stream.cc.o

.PHONY : src/stream.o

# target to build an object file
src/stream.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/stream.cc.o
.PHONY : src/stream.cc.o

src/stream.i: src/stream.cc.i

.PHONY : src/stream.i

# target to preprocess a source file
src/stream.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/stream.cc.i
.PHONY : src/stream.cc.i

src/stream.s: src/stream.cc.s

.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/stream.cc.s
.PHONY : src/stream.cc.s

src/tcpServer.o: src/tcpServer.cc.o

.PHONY : src/tcpServer.o

# target to build an object file
src/tcpServer.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/tcpServer.cc.o
.PHONY : src/tcpServer.cc.o

src/tcpServer.i: src/tcpServer.cc.i

.PHONY : src/tcpServer.i

# target to preprocess a source file
src/tcpServer.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/tcpServer.cc.i
.PHONY : src/tcpServer.cc.i

src/tcpServer.s: src/tcpServer.cc.s

.PHONY : src/tcpServer.s

# target to generate assembly for a file
src/tcpServer.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/tcpServer.cc.s
.PHONY : src/tcpServer.cc.s

src/timer.o: src/timer.cc.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cc.o:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/timer.cc.o
.PHONY : src/timer.cc.o

src/timer.i: src/timer.cc.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cc.i:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/timer.cc.i
.PHONY : src/timer.cc.i

src/timer.s: src/timer.cc.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cc.s:
	$(MAKE) -f CMakeFiles/MyLibrary.dir/build.make CMakeFiles/MyLibrary.dir/src/timer.cc.s
.PHONY : src/timer.cc.s

test/test_address.o: test/test_address.cc.o

.PHONY : test/test_address.o

# target to build an object file
test/test_address.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_address.cc.o
.PHONY : test/test_address.cc.o

test/test_address.i: test/test_address.cc.i

.PHONY : test/test_address.i

# target to preprocess a source file
test/test_address.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_address.cc.i
.PHONY : test/test_address.cc.i

test/test_address.s: test/test_address.cc.s

.PHONY : test/test_address.s

# target to generate assembly for a file
test/test_address.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_address.cc.s
.PHONY : test/test_address.cc.s

test/test_coroutine.o: test/test_coroutine.cc.o

.PHONY : test/test_coroutine.o

# target to build an object file
test/test_coroutine.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine.cc.o
.PHONY : test/test_coroutine.cc.o

test/test_coroutine.i: test/test_coroutine.cc.i

.PHONY : test/test_coroutine.i

# target to preprocess a source file
test/test_coroutine.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine.cc.i
.PHONY : test/test_coroutine.cc.i

test/test_coroutine.s: test/test_coroutine.cc.s

.PHONY : test/test_coroutine.s

# target to generate assembly for a file
test/test_coroutine.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine.cc.s
.PHONY : test/test_coroutine.cc.s

test/test_coroutine2.o: test/test_coroutine2.cc.o

.PHONY : test/test_coroutine2.o

# target to build an object file
test/test_coroutine2.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine2.cc.o
.PHONY : test/test_coroutine2.cc.o

test/test_coroutine2.i: test/test_coroutine2.cc.i

.PHONY : test/test_coroutine2.i

# target to preprocess a source file
test/test_coroutine2.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine2.cc.i
.PHONY : test/test_coroutine2.cc.i

test/test_coroutine2.s: test/test_coroutine2.cc.s

.PHONY : test/test_coroutine2.s

# target to generate assembly for a file
test/test_coroutine2.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_coroutine2.cc.s
.PHONY : test/test_coroutine2.cc.s

test/test_fdManager.o: test/test_fdManager.cc.o

.PHONY : test/test_fdManager.o

# target to build an object file
test/test_fdManager.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_fdManager.cc.o
.PHONY : test/test_fdManager.cc.o

test/test_fdManager.i: test/test_fdManager.cc.i

.PHONY : test/test_fdManager.i

# target to preprocess a source file
test/test_fdManager.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_fdManager.cc.i
.PHONY : test/test_fdManager.cc.i

test/test_fdManager.s: test/test_fdManager.cc.s

.PHONY : test/test_fdManager.s

# target to generate assembly for a file
test/test_fdManager.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_fdManager.cc.s
.PHONY : test/test_fdManager.cc.s

test/test_hook.o: test/test_hook.cc.o

.PHONY : test/test_hook.o

# target to build an object file
test/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_hook.cc.o
.PHONY : test/test_hook.cc.o

test/test_hook.i: test/test_hook.cc.i

.PHONY : test/test_hook.i

# target to preprocess a source file
test/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_hook.cc.i
.PHONY : test/test_hook.cc.i

test/test_hook.s: test/test_hook.cc.s

.PHONY : test/test_hook.s

# target to generate assembly for a file
test/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_hook.cc.s
.PHONY : test/test_hook.cc.s

test/test_iomanager.o: test/test_iomanager.cc.o

.PHONY : test/test_iomanager.o

# target to build an object file
test/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_iomanager.cc.o
.PHONY : test/test_iomanager.cc.o

test/test_iomanager.i: test/test_iomanager.cc.i

.PHONY : test/test_iomanager.i

# target to preprocess a source file
test/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_iomanager.cc.i
.PHONY : test/test_iomanager.cc.i

test/test_iomanager.s: test/test_iomanager.cc.s

.PHONY : test/test_iomanager.s

# target to generate assembly for a file
test/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_iomanager.cc.s
.PHONY : test/test_iomanager.cc.s

test/test_scheduler.o: test/test_scheduler.cc.o

.PHONY : test/test_scheduler.o

# target to build an object file
test/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler.cc.o
.PHONY : test/test_scheduler.cc.o

test/test_scheduler.i: test/test_scheduler.cc.i

.PHONY : test/test_scheduler.i

# target to preprocess a source file
test/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler.cc.i
.PHONY : test/test_scheduler.cc.i

test/test_scheduler.s: test/test_scheduler.cc.s

.PHONY : test/test_scheduler.s

# target to generate assembly for a file
test/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler.cc.s
.PHONY : test/test_scheduler.cc.s

test/test_scheduler2.o: test/test_scheduler2.cc.o

.PHONY : test/test_scheduler2.o

# target to build an object file
test/test_scheduler2.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler2.cc.o
.PHONY : test/test_scheduler2.cc.o

test/test_scheduler2.i: test/test_scheduler2.cc.i

.PHONY : test/test_scheduler2.i

# target to preprocess a source file
test/test_scheduler2.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler2.cc.i
.PHONY : test/test_scheduler2.cc.i

test/test_scheduler2.s: test/test_scheduler2.cc.s

.PHONY : test/test_scheduler2.s

# target to generate assembly for a file
test/test_scheduler2.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_scheduler2.cc.s
.PHONY : test/test_scheduler2.cc.s

test/test_socket_client.o: test/test_socket_client.cc.o

.PHONY : test/test_socket_client.o

# target to build an object file
test/test_socket_client.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_client.cc.o
.PHONY : test/test_socket_client.cc.o

test/test_socket_client.i: test/test_socket_client.cc.i

.PHONY : test/test_socket_client.i

# target to preprocess a source file
test/test_socket_client.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_client.cc.i
.PHONY : test/test_socket_client.cc.i

test/test_socket_client.s: test/test_socket_client.cc.s

.PHONY : test/test_socket_client.s

# target to generate assembly for a file
test/test_socket_client.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_client.cc.s
.PHONY : test/test_socket_client.cc.s

test/test_socket_server.o: test/test_socket_server.cc.o

.PHONY : test/test_socket_server.o

# target to build an object file
test/test_socket_server.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_server.cc.o
.PHONY : test/test_socket_server.cc.o

test/test_socket_server.i: test/test_socket_server.cc.i

.PHONY : test/test_socket_server.i

# target to preprocess a source file
test/test_socket_server.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_server.cc.i
.PHONY : test/test_socket_server.cc.i

test/test_socket_server.s: test/test_socket_server.cc.s

.PHONY : test/test_socket_server.s

# target to generate assembly for a file
test/test_socket_server.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_socket_server.cc.s
.PHONY : test/test_socket_server.cc.s

test/test_stream.o: test/test_stream.cc.o

.PHONY : test/test_stream.o

# target to build an object file
test/test_stream.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_stream.cc.o
.PHONY : test/test_stream.cc.o

test/test_stream.i: test/test_stream.cc.i

.PHONY : test/test_stream.i

# target to preprocess a source file
test/test_stream.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_stream.cc.i
.PHONY : test/test_stream.cc.i

test/test_stream.s: test/test_stream.cc.s

.PHONY : test/test_stream.s

# target to generate assembly for a file
test/test_stream.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_stream.cc.s
.PHONY : test/test_stream.cc.s

test/test_tcp_server.o: test/test_tcp_server.cc.o

.PHONY : test/test_tcp_server.o

# target to build an object file
test/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_tcp_server.cc.o
.PHONY : test/test_tcp_server.cc.o

test/test_tcp_server.i: test/test_tcp_server.cc.i

.PHONY : test/test_tcp_server.i

# target to preprocess a source file
test/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_tcp_server.cc.i
.PHONY : test/test_tcp_server.cc.i

test/test_tcp_server.s: test/test_tcp_server.cc.s

.PHONY : test/test_tcp_server.s

# target to generate assembly for a file
test/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_tcp_server.cc.s
.PHONY : test/test_tcp_server.cc.s

test/test_timer.o: test/test_timer.cc.o

.PHONY : test/test_timer.o

# target to build an object file
test/test_timer.cc.o:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_timer.cc.o
.PHONY : test/test_timer.cc.o

test/test_timer.i: test/test_timer.cc.i

.PHONY : test/test_timer.i

# target to preprocess a source file
test/test_timer.cc.i:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_timer.cc.i
.PHONY : test/test_timer.cc.i

test/test_timer.s: test/test_timer.cc.s

.PHONY : test/test_timer.s

# target to generate assembly for a file
test/test_timer.cc.s:
	$(MAKE) -f CMakeFiles/MyTests.dir/build.make CMakeFiles/MyTests.dir/test/test_timer.cc.s
.PHONY : test/test_timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MyTests"
	@echo "... MyLibrary"
	@echo "... src/address.o"
	@echo "... src/address.i"
	@echo "... src/address.s"
	@echo "... src/coroutine.o"
	@echo "... src/coroutine.i"
	@echo "... src/coroutine.s"
	@echo "... src/fdManager.o"
	@echo "... src/fdManager.i"
	@echo "... src/fdManager.s"
	@echo "... src/hook.o"
	@echo "... src/hook.i"
	@echo "... src/hook.s"
	@echo "... src/iomanager.o"
	@echo "... src/iomanager.i"
	@echo "... src/iomanager.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/tcpServer.o"
	@echo "... src/tcpServer.i"
	@echo "... src/tcpServer.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... test/test_address.o"
	@echo "... test/test_address.i"
	@echo "... test/test_address.s"
	@echo "... test/test_coroutine.o"
	@echo "... test/test_coroutine.i"
	@echo "... test/test_coroutine.s"
	@echo "... test/test_coroutine2.o"
	@echo "... test/test_coroutine2.i"
	@echo "... test/test_coroutine2.s"
	@echo "... test/test_fdManager.o"
	@echo "... test/test_fdManager.i"
	@echo "... test/test_fdManager.s"
	@echo "... test/test_hook.o"
	@echo "... test/test_hook.i"
	@echo "... test/test_hook.s"
	@echo "... test/test_iomanager.o"
	@echo "... test/test_iomanager.i"
	@echo "... test/test_iomanager.s"
	@echo "... test/test_scheduler.o"
	@echo "... test/test_scheduler.i"
	@echo "... test/test_scheduler.s"
	@echo "... test/test_scheduler2.o"
	@echo "... test/test_scheduler2.i"
	@echo "... test/test_scheduler2.s"
	@echo "... test/test_socket_client.o"
	@echo "... test/test_socket_client.i"
	@echo "... test/test_socket_client.s"
	@echo "... test/test_socket_server.o"
	@echo "... test/test_socket_server.i"
	@echo "... test/test_socket_server.s"
	@echo "... test/test_stream.o"
	@echo "... test/test_stream.i"
	@echo "... test/test_stream.s"
	@echo "... test/test_tcp_server.o"
	@echo "... test/test_tcp_server.i"
	@echo "... test/test_tcp_server.s"
	@echo "... test/test_timer.o"
	@echo "... test/test_timer.i"
	@echo "... test/test_timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

